<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartSolutionsLab.Roomy.Application.Contracts</RootNamespace>
    <AssemblyName>SmartSolutionsLab.Roomy.Application.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../shared-kernel/src/Roomy.SharedKernel.csproj" />
  </ItemGroup>

</Project>
