import { ModuleWithProviders } from '@angular/core';
import { TranslocoTestingModule } from '@jsverse/transloco';

// Test-only Transloco setup for this library's components. It carries just the keys the attendance
// screens use, so the library's specs stay independent of the app's global translation files (importing
// those would cross the context:web boundary). Excluded from the library build. Kept in key parity with
// apps/web/public/i18n/{en,de}.json (FR-010).
const english = {
  shared: {
    list: {
      loadMore: 'Load more',
      loading: 'Loading…',
      endOfList: 'End of list',
    },
  },
  attendance: {
    reserve: {
      title: 'Reserve a place',
      loading: 'Loading…',
      loadError: 'We could not load the offices.',
      empty: 'No offices or rooms are available to book yet.',
      officeLabel: 'Office',
      officePlaceholder: 'Select an office',
      dayLabel: 'Day',
      dayPlaceholder: 'Select a day',
      roomsHeading: 'Rooms',
      capacityLabel: '{{capacity}} places',
      free: '{{remaining}} of {{capacity}} free',
      full: 'Full',
      confirm: 'Reserve',
      reserved: 'Reserved {{room}} for {{date}}.',
      errors: {
        roomFull: 'That room is full for the chosen day.',
        alreadyReserved: 'You already have a reservation that day.',
        notBookable: 'Only working days within the next two weeks can be booked.',
        unknownRoom: 'That room is no longer available.',
        retry: 'Someone just took the last place. Please try again.',
        generic: 'We could not reserve the place. Please try again.',
      },
    },
    mine: {
      title: 'My reservations',
      loading: 'Loading…',
      loadError: 'We could not load your reservations.',
      empty: 'You have no reservations yet.',
      reserveLink: 'Reserve a place',
      upcomingHeading: 'Upcoming',
      pastHeading: 'Past',
      cancel: 'Cancel',
      cancelReservation: 'Cancel the reservation for {{room}} on {{date}}',
      change: 'Change',
      cancelled: 'Reservation cancelled.',
      errors: {
        pastImmutable: 'Past reservations cannot be changed.',
        generic: 'We could not cancel the reservation. Please try again.',
      },
    },
    occupancy: {
      title: 'Occupancy',
      officeLabel: 'Office',
      officePlaceholder: 'Select an office',
      roomLabel: 'Room',
      allRooms: 'All rooms',
      rangeLabel: 'Range',
      presetDay: 'Day',
      presetWeek: 'Week',
      presetMonth: 'Month',
      dateLabel: 'Date',
      loading: 'Loading…',
      loadError: 'We could not load the occupancy.',
      empty: 'No offices or rooms are available yet.',
      unknownScope: 'That office or room is no longer available.',
      officeOccupied: 'Office: {{occupied}} of {{capacity}} occupied',
      roomOccupied: '{{occupied}} of {{capacity}} occupied',
      full: 'Full',
      bookedHeading: 'Booked',
    },
    calendar: {
      title: 'Occupancy calendar',
      previousMonth: 'Previous month',
      nextMonth: 'Next month',
      mine: 'You have a reservation',
      occupied: '{{occupied}}/{{capacity}}',
    },
    onBehalf: {
      title: 'Reserve on behalf',
      searchLabel: 'Search employees',
      searchPlaceholder: 'Type a name',
      noMatches: 'No employees match your search.',
      matchCount: '{{count}} matching employees',
      employeeLabel: 'Employee',
      employeePlaceholder: 'Select an employee',
      loading: 'Loading…',
      loadError: 'We could not load the employees.',
      emptyEmployees: 'There are no employees yet.',
      prompt: 'Select an employee to reserve or cancel on their behalf.',
      reservationsHeading: 'Their reservations',
      upcomingHeading: 'Upcoming',
      pastHeading: 'Past',
      noReservations: 'This employee has no reservations.',
      cancel: 'Cancel',
      cancelReservation: 'Cancel the reservation for {{room}} on {{date}}',
      cancelled: 'Reservation cancelled.',
      errors: {
        pastImmutable: 'Past reservations cannot be changed.',
        generic: 'We could not cancel the reservation. Please try again.',
      },
    },
  },
};

const german = {
  shared: {
    list: {
      loadMore: 'Mehr laden',
      loading: 'Wird geladen…',
      endOfList: 'Ende der Liste',
    },
  },
  attendance: {
    reserve: {
      title: 'Platz reservieren',
      loading: 'Wird geladen…',
      loadError: 'Die Büros konnten nicht geladen werden.',
      empty: 'Es sind noch keine Büros oder Räume buchbar.',
      officeLabel: 'Büro',
      officePlaceholder: 'Büro auswählen',
      dayLabel: 'Tag',
      dayPlaceholder: 'Tag auswählen',
      roomsHeading: 'Räume',
      capacityLabel: '{{capacity}} Plätze',
      free: '{{remaining}} von {{capacity}} frei',
      full: 'Belegt',
      confirm: 'Reservieren',
      reserved: '{{room}} für {{date}} reserviert.',
      errors: {
        roomFull: 'Dieser Raum ist am gewählten Tag belegt.',
        alreadyReserved: 'Sie haben an diesem Tag bereits eine Reservierung.',
        notBookable: 'Nur Werktage innerhalb der nächsten zwei Wochen sind buchbar.',
        unknownRoom: 'Dieser Raum ist nicht mehr verfügbar.',
        retry: 'Jemand hat gerade den letzten Platz belegt. Bitte erneut versuchen.',
        generic: 'Der Platz konnte nicht reserviert werden. Bitte erneut versuchen.',
      },
    },
    mine: {
      title: 'Meine Reservierungen',
      loading: 'Wird geladen…',
      loadError: 'Ihre Reservierungen konnten nicht geladen werden.',
      empty: 'Sie haben noch keine Reservierungen.',
      reserveLink: 'Platz reservieren',
      upcomingHeading: 'Bevorstehend',
      pastHeading: 'Vergangen',
      cancel: 'Stornieren',
      cancelReservation: 'Reservierung für {{room}} am {{date}} stornieren',
      change: 'Ändern',
      cancelled: 'Reservierung storniert.',
      errors: {
        pastImmutable: 'Vergangene Reservierungen können nicht geändert werden.',
        generic: 'Die Reservierung konnte nicht storniert werden. Bitte erneut versuchen.',
      },
    },
    occupancy: {
      title: 'Belegung',
      officeLabel: 'Büro',
      officePlaceholder: 'Büro auswählen',
      roomLabel: 'Raum',
      allRooms: 'Alle Räume',
      rangeLabel: 'Zeitraum',
      presetDay: 'Tag',
      presetWeek: 'Woche',
      presetMonth: 'Monat',
      dateLabel: 'Datum',
      loading: 'Wird geladen…',
      loadError: 'Die Belegung konnte nicht geladen werden.',
      empty: 'Es sind noch keine Büros oder Räume vorhanden.',
      unknownScope: 'Dieses Büro oder dieser Raum ist nicht mehr verfügbar.',
      officeOccupied: 'Büro: {{occupied}} von {{capacity}} belegt',
      roomOccupied: '{{occupied}} von {{capacity}} belegt',
      full: 'Belegt',
      bookedHeading: 'Gebucht',
    },
    calendar: {
      title: 'Belegungskalender',
      previousMonth: 'Voriger Monat',
      nextMonth: 'Nächster Monat',
      mine: 'Sie haben eine Reservierung',
      occupied: '{{occupied}}/{{capacity}}',
    },
    onBehalf: {
      title: 'Im Namen reservieren',
      searchLabel: 'Mitarbeiter suchen',
      searchPlaceholder: 'Namen eingeben',
      noMatches: 'Keine Mitarbeiter entsprechen Ihrer Suche.',
      matchCount: '{{count}} passende Mitarbeiter',
      employeeLabel: 'Mitarbeiter',
      employeePlaceholder: 'Mitarbeiter auswählen',
      loading: 'Wird geladen…',
      loadError: 'Die Mitarbeiter konnten nicht geladen werden.',
      emptyEmployees: 'Es gibt noch keine Mitarbeiter.',
      prompt: 'Wählen Sie einen Mitarbeiter, um in seinem Namen zu reservieren oder zu stornieren.',
      reservationsHeading: 'Seine Reservierungen',
      upcomingHeading: 'Bevorstehend',
      pastHeading: 'Vergangen',
      noReservations: 'Dieser Mitarbeiter hat keine Reservierungen.',
      cancel: 'Stornieren',
      cancelReservation: 'Reservierung für {{room}} am {{date}} stornieren',
      cancelled: 'Reservierung storniert.',
      errors: {
        pastImmutable: 'Vergangene Reservierungen können nicht geändert werden.',
        generic: 'Die Reservierung konnte nicht storniert werden. Bitte erneut versuchen.',
      },
    },
  },
};

export function importAttendanceTestTransloco(): ModuleWithProviders<TranslocoTestingModule> {
  return TranslocoTestingModule.forRoot({
    langs: { en: english, de: german },
    translocoConfig: {
      availableLangs: ['en', 'de'],
      defaultLang: 'en',
      reRenderOnLangChange: true,
    },
    preloadLangs: true,
  });
}
