<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SmartSolutionsLab.Roomy.Contracts.Identity</RootNamespace>
    <AssemblyName>SmartSolutionsLab.Roomy.Contracts.Identity</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../application-contracts/src/Roomy.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
