// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSolutionsLab.Roomy.Organization.Infrastructure.Persistence;

#nullable disable

namespace SmartSolutionsLab.Roomy.Organization.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrganizationDbContext))]
    partial class OrganizationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSolutionsLab.Roomy.Organization.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Identifier")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Roomy.Organization.Domain.Offices.Office", b =>
                {
                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid")
                        .HasColumnName("identifier");

                    b.Property<Guid>("CompanyIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("company_identifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Identifier")
                        .HasName("pk_offices");

                    b.HasIndex("CompanyIdentifier", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_offices_company_identifier_name");

                    b.ToTable("offices", (string)null);
                });

            modelBuilder.Entity("SmartSolutionsLab.Roomy.Organization.Domain.Offices.Office", b =>
                {
                    b.OwnsMany("SmartSolutionsLab.Roomy.Organization.Domain.Offices.Room", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("Identifier")
                                .HasColumnType("uuid")
                                .HasColumnName("identifier");

                            b1.Property<int>("Capacity")
                                .HasColumnType("integer")
                                .HasColumnName("capacity");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<Guid>("OfficeIdentifier")
                                .HasColumnType("uuid")
                                .HasColumnName("office_identifier");

                            b1.HasKey("Identifier")
                                .HasName("pk_rooms");

                            b1.HasIndex("OfficeIdentifier", "Name")
                                .IsUnique()
                                .HasDatabaseName("ux_rooms_office_identifier_name");

                            b1.ToTable("rooms", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OfficeIdentifier")
                                .HasConstraintName("fk_rooms_offices_office_identifier");
                        });

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
